import numpy as np
i=np.array([[0.05],[0.10]])
w_input=np.array([[0.15,0.20],[0.20,0.30]])
w_hidden=np.array([[0.40,0.45],[0.50,0.55]])
b1=0.35
b2=0.60
lea=0.5
expected=np.array([[0.01,0.99]])
neth=b1+np.matmul(w_input,i)
outh=1/(1+np.exp(-neth))
neto=b2+np.matmul(w_hidden,outh)
outo=1/(1+np.exp(-neto))
e=(expected.transpose()-outo)**2/2
totale=e[0]+e[1]
deouto=-(expected.transpose()-outo)
doutoneto=(outo)*(1-outo)
dew=deouto*doutoneto*outh
dnetouth1=np.array([w_hidden[:,0]])	
dnetouth1_tran=dnetouth1.transpose()
deouth1=deouto*doutoneto*dnetouth1_tran
douthneth=(outh)*(1-outh)
dnethw=i
dnetouth2=np.array([w_hidden[:,1]])	
dnetouth2_tran=dnetouth1.transpose()
deouth2=deouto*doutoneto*dnetouth2_tran
detouth1=deouth1[0]+deouth1[1]
detouth2=deouth2[0]+deouth2[1]
detw13=detouth1*douthneth*dnethw
print(detw13)
detw24=detouth2*douthneth*dnethw
detw=np.concatenate((detw13,detw24),axis=1)
print(detw)
w_input=w_input-lea*detw
print(w_input)